FROM ubuntu:20.04
LABEL "Author"="Venkata Sai"
LABEL "Project"= " Elastic Search"
ENV DEBIAN_FRONTEND = noniteratcive
RUN apt-get update && \
    apt-get install -y wget openjdk-11-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.0-linux-x86_64.tar.gz | tar -xzf - -C /opt && \
    mv /opt/elasticsearch-7.17.0 /opt/elasticsearch


WORKDIR /opt/elasticsearch


RUN mkdir -p /var/lib/elasticsearch


COPY elasticsearch.yml /opt/elasticsearch/config/elasticsearch.yml


EXPOSE 9200 9300


USER 1000:1000


CMD ["elasticsearch"]

